service: bits

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${env:AWS_STAGE, 'prod'}
  region: ${env:AWS_REGION, 'us-east-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: 
        - "arn:aws:s3:::${self:custom.REPORTS_BUCKET}/*"
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: 
       - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.SUBSCRIPTION_DYNAMODB_TABLE}"
       - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.REPORTS_DYNAMODB_TABLE}"

custom:
  DOMAIN_SUFFIX: ${env:DOMAIN_SUFFIX,'bits_test'}
  SUBSCRIPTION_DYNAMODB_TABLE: ${env:SUBSCRIPTION_DYNAMODB_TABLE,'bits-subscription-dev'}
  REPORTS_DYNAMODB_TABLE: ${env:REPORTS_DYNAMODB_TABLE,'bits-reports-dev'}
  REPORTS_BUCKET: ${env:REPORTS_BUCKET,'bits-reports-dev'}
  REPORT_DLQ: ${env:REPORT_DLQ,'bits-reports-dlq-dev'}

package:
  exclude:
    - test/**/*
    - .eslintignore
    - .eslintrc.js
    - .prettierignore
    - .prettierrc.json
    - jest.config.js
    - README.md
    - tsconfig.json
    - tsconfig.test.json
    - package-lock.json
  include:
    - handler.ts
    - src/**/*

functions:
  authorizerFunc:
    handler: handler.authorizerFunc

  healthcheck:
    handler: handler.healthCheck
    events:
      - http:
          path: /healthcheck
          method: get
    timeout: ${env:LAMBDA_TIMEOUT_IN_SECS, 10}
    memorySize: ${env:LAMBDA_MEMORY_SIZE, 512}
    reservedConcurreny: ${env:LAMBDA_RESERVED_CONCURRENCY, 5}
  
  addSubscription:
    handler: handler.addSubscription
    events:
      - http:
          path: /subscription
          method: post
          contentType: application/json
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: ^Bearer\s[a-f0-9-]{36}$
            type: token
    environment:
      NODE_ENV: ${self:provider.stage}
      SUBSCRIPTION_DYNAMODB_TABLE: ${self:custom.SUBSCRIPTION_DYNAMODB_TABLE}
    timeout: ${env:LAMBDA_TIMEOUT_IN_SECS, 10}
    memorySize: ${env:LAMBDA_MEMORY_SIZE, 512}
    reservedConcurreny: ${env:LAMBDA_RESERVED_CONCURRENCY, 5}

  calculateSubscription:
    handler: handler.calculateSubscription
    evnironment:
      NODE_ENV: ${self:provider.stage}
      REPORT_DYNAMODB_TABLE: ${self:custom.REPORTS_DYNAMODB_TABLE}
      S3_REPORT_BUCKET: ${self:custom.REPORTS_BUCKET}
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [subscriptionTable, StreamArn]
          destinations:
            onFailure: 
              arn:
                Fn::GetAtt:
                  - ReportDLQ
                  - Arn
              type: sqs

resources:
  - ${file(resources/dynamo-db.yml)}
  - ${file(resources/reports-dlq.yml)}
  - ${file(resources/reports-s3.yml)}