Resources:
  CognitoUserPoolForEndUsers:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:provider.stage}-user-pool-for-end-users
      UsernameAttributes:
        - phone_number
      MfaConfiguration: OFF

  CognitoUserPoolForEndUsersCustomDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: ${env:AWS_AUTH_DOMAIN_NAME, 'bitstest'}
      UserPoolId:
        Ref: CognitoUserPoolForEndUsers

  CognitoUserPoolClientForEndUsers:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:provider.stage}-user-pool-client-for-end-users
      UserPoolId:
        Ref: CognitoUserPoolForEndUsers
      ExplicitAuthFlows:
        - ALLOW_CUSTOM_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      RefreshTokenValidity: 60
      PreventUserExistenceErrors: ENABLED

Outputs:
  UserPoolIdForEndUsers:
    Value:
      Ref: CognitoUserPoolForEndUsers
  UserPoolClientIdForEndUsers:
    Value:
      Ref: CognitoUserPoolClientForEndUsers