Resources:
  ReportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.REPORTS_BUCKET}
      AccelerateConfiguration:
        AccelerationStatus: 'Enabled'
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - 'GET'
            MaxAge: 3000
